(source gnu)
(source melpa-stable)

(depends-on "init-loader")
(depends-on "use-package")

(depends-on "win-switch")

(depends-on "ace-jump-mode")
(depends-on "browse-kill-ring")
(depends-on "expand-region")
(depends-on "undo-tree")

(depends-on "projectile")
(depends-on "perspective")
(depends-on "persp-projectile")
(depends-on "monokai-theme")
(depends-on "linum-relative")
(depends-on "smart-mode-line")
(depends-on "smex")
(depends-on "magit")
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "fuzzy")
(depends-on "rainbow-delimiters")
(depends-on "paredit")
(depends-on "auto-complete")
(depends-on "eval-sexp-fu")
(depends-on "cyberpunk-theme")

(depends-on "ruby-mode")
(depends-on "rspec-mode")
(depends-on "scss-mode")
(depends-on "coffee-mode")
(depends-on "slim-mode")
(depends-on "js2-mode")
(depends-on "markdown-mode")
(depends-on "haskell-mode")

(depends-on "indent-guide")
