(source gnu)
(source melpa)

(depends-on "init-loader")
(depends-on "use-package")

(depends-on "ace-jump-mode")
(depends-on "browse-kill-ring")
(depends-on "expand-region")
(depends-on "undo-tree")
(depends-on "scratch")
(depends-on "volatile-highlights")
;; (depends-on "highlight-tail")
;; (depends-on "quick-jump" :git "https://github.com/jixiuf/quick-jump")
(depends-on "projectile")
(depends-on "perspective")
(depends-on "persp-projectile")
(depends-on "monokai-theme")
(depends-on "linum-relative")
(depends-on "smart-mode-line")
(depends-on "dired-details+")
(depends-on "smex")

(depends-on "git-commit-mode")
(depends-on "magit")

(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "ac-cider")
(depends-on "fuzzy")
(depends-on "popup")
(depends-on "clj-refactor")
(depends-on "uuid")
(depends-on "highlight")
(depends-on "mic-paren")
(depends-on "rainbow-delimiters")
(depends-on "paredit")
(depends-on "align-cljlet")
(depends-on "auto-complete")
(depends-on "eval-sexp-fu")

(depends-on "ruby-mode")
(depends-on "rspec-mode")

(depends-on "scss-mode")
(depends-on "coffee-mode")
(depends-on "slim-mode")
(depends-on "js2-mode")
(depends-on "markdown-mode")
(depends-on "haskell-mode")
(depends-on "scala-mode")